# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "favicon.png"
    keywords:

# Jump Links Settings
url:
    rss: "/atom.xml"
    daily_pic: "#"
    logo: "/"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
#scheme: Nexus
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "好运不会眷顾傻瓜"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true
    pjax: false

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    markdown: Github
    #entry_excerpt: 80
    code_highlight: atom-one-dark

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    #purecolor: "#F5F5F5"
    bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.jpg"
    avatar: "/img/myavatar.jpg"
    daily_pic: "/img/daily_pic.jpg"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    #upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/material-"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: 172214722@qq.com
    twitter:
    facebook:
    googleplus: "https://www.google.com/"
    weibo: "http://weibo.com/"
    instagram:
    tumblr:
    github: "https://github.com/kuaiman"
    linkedin: 
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: true
    qq: true
    telegram: false

# Sidebar User Dropdown
dropdown:
    Email Me:
        link: "mailto:172214722@qq.com"
        icon: email

# Sidebar Categories Switch
sidebar_categories: false

# Pages Menu
pages:
    关于我:
      link: "/About"
      icon: person
    标签云:
      link: "/tags"
      icon: "cloud circle"
    友情链接:
      link: "/links"
      icon: link


# Qrcode for redirect at other device
qrcode: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value:
#     duoshuo | disqus
comment:
    use: duoshuo
    shortname: IO10
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "/js/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: swiftype
    swiftype_key: EeKmzzQyZTH_Tu1Sx2aR

# Leancloud Views
leancloud:
    enable: true
    app_id: BvJcby3BNlDWQWq9qjji2NEK-gzGzoHsz
    app_key: 3IcnGJ5Ad8PCCzUe2vLuDIaz
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
